language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
          env: components=low
        - php: 5.6
          env: components=high
        - php: hhvm
    allow_failures:
        - php: hhvm

env:
    global:
        - components=no

before_script:
  - if [ "$components" = "no" ]; then composer install -n; fi;
  - if [ "$components" = "high" ]; then composer update -n; fi;
  - if [ "$components" = "low" ]; then composer install -n --prefer-lowest --prefer-stable; fi;

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" && "$components" = "high" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" && "$components" = "low" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
